spring.application.name=empre-go


# 1. Mudamos de 'mem:escola' para 'file:./dados/escola'
spring.datasource.url=jdbc:h2:file:./dados/emprego
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 2. Adicionamos essa linha para o Hibernate não apagar os dados ao reiniciar
spring.jpa.hibernate.ddl-auto=update

# Configurações do Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=8080